import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Parse from "parse/node";
import {initParseInServerSide} from "@/utils/parse/initParseServerSide";
import MainLayout from "@/layout/MainLayout";
import {PropsWithChildren} from "react";

initParseInServerSide();

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout(props: PropsWithChildren) {
    const {children} = props;
    Parse.Cloud.run('hello', {
        a: 1,
        b: 2
    }).then((result) => {
            console.log("Cloud function result:", result);

        }
    )
    return (
        <html lang='en'>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <MainLayout>
            {children}
        </MainLayout>
        </body>
        </html>
    );
}
